---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/ritceynoah/pcf-attendee-service-code   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: noah.ritcey
    space: development
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

