---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: http://github.com/ritceynoah/pcf-attendee-service-code.git
    branch: master
- name: deploy-attendee-service
  type: cf
  source:
    api: api.https://api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: noah.ritcey
    space: development
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-semisynthetic-rose.cfapps.io